### ISSUE TITLE
(1st) Implement `SHOW entry` route

### ISSUE THREAD

**Issue by h4w5** [h4w5/wdinstagram_collaboration_challenge#1]
Hi @jgescobar!

Here's what needs to be done:

I have written out all of the client-side logic (templating, AJAX, etc.) to implement a show route for an entry in our app. However, the show route hasn't been implemented on the server!

You must,

1. Turn on the route (`/api/entries/:id`), **[which has been stubbed out already](https://github.com/h4w5/wdinstagram_challenge/blob/master/routes/api_routes.js#L7)**.
2. Write the handler for the route, **which shall respond with the _JSON_ version of whatever entry was requested**. [The controller is here](https://github.com/h4w5/wdinstagram_challenge/blob/master/controllers/entries.js#L15).

You'll know it works when you trigger the show page render, and you can only see that specific entry.

For example:

<img src="https://i.imgur.com/sUI2cRO.png" width="100"> &nbsp; **=> SHOULD BECOME =>** &nbsp; <img src="https://i.imgur.com/p690kVy.png" width="100">

> Note: on the client, you trigger the route by clicking on an entry's picture or the author.

---
Here is the client code:

[The trigger handler looks like](https://github.com/h4w5/wdinstagram_challenge/blob/master/public/js/main.js#L13-L32):

```js
$showEntryButtons = $(".show-link");
// ...
$showEntryButtons.on("click", function(evt) {
  var entryId = $(evt.currentTarget).closest(".entry").attr("id");

  console.log("show triggered!", entryId);
  fetchEntry(entryId);
});
```

[The fetch itself is](https://github.com/h4w5/wdinstagram_challenge/blob/master/public/js/main.js#L73-L88):

```js
function fetchEntry(entryId) {
  $.ajax({
    method: "GET",
    url:    "/api/entries/" + entryId
  })
  .then(
    function(res) {
      console.log("Success:", res);
      renderAndAppendEntry(res.data);
    },
    function(err) {
      console.log("Failed:", err);
      alert(err.message);
    }
  );
}
```

**Comment by h4w5** [comment]
If you have any questions or need any help, just respond in this issue!

**Comment by jgescobar** [comment]
Ok thank you :)


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: Philip Hughes <notifications@github.com> Date: 3/24/2016  6:47 PM  (GMT-08:00) To: h4w5/wdinstagram_challenge <wdinstagram_challenge@noreply.github.com> Cc: Jasmine Guzman-Escobar <jasmineguzmanescobar@yahoo.com> Subject: Re: [wdinstagram_challenge] Implement `SHOW entry` route (#1) 
If you have any questions or need any help, just respond in this issue!

**Comment by jgescobar** [comment]
Hi Phil, Im with Duane and Dave and we were trying to understand how to merge and pull stuff from the upstream (your master branch) into my origin master and my current working branch but we are all confused as to what exactly is being pulled and pushed. Am I supposed to be working off of new or sub branches or can i just work and update my master? I think the correct way is working off branches but if i'm going to merge and make pull requests from my working branches onto my master, why not just work off master? Basically, can I just push from my origin master? Since no one else is merging stuff your way? We are all kinda confused.

**Comment by jgescobar** [comment]
AAU I would like to see one specific photo. 

What error am I getting? 

- This is the error I continue to get on my console when I try to implement the show function. The screen shot is below : 
https://i.imgur.com/z3owrBa.png 

What have I already attempted in trying to fix the error?
I set the id = to some params but I have no clue how to fix the error I continue to get since its saying its an issue with jquery. Where would I start searching in jquery? What file? 

Thank you, 
Jas

**Comment by h4w5** [comment]
Good question! I just posted a response about the error in the PR. Here it is: pull request #7

**Comment by h4w5** [comment]
As far as the pushing and pulling go, **[follow the team workflow](https://github.com/ga-students/WDI_DTLA_8/blob/master/resources/cheatsheets/git_team_cheatsheet.md#working-on-feature-branches)**. You have nothing to pull yet, though, since you have all the code already! Once I accept a PR from you, you can use `git pull upstream master` to get the accepted and merged code.

**Comment by jgescobar** [comment]
AAU I want the show function to work.

New Error I get 
https://i.imgur.com/GBQgXAj.png

Function I re-wrote where I got this new error
https://i.imgur.com/89m1Z0r.png

Im not getting any localhost issues now, im getting jquery and lodash template issues. Where could i fix this?

**Comment by jgescobar** [comment]
so for some weird reason, when I went to main.js and deleted the .data part of renderAndAppendEntry(res.data); the function I wrote for Show() returns the 1 image. I hope deleting the .data will not give me future errors for the next issues I need to work on. I am going to commit and push the working show function now.

**Comment by h4w5** [comment]
Alright: for this issue I'm giving you 0.75 out of 1.

You got the basic feature correct, but you sent the PR from you master branch instead of a working branch. You also failed to send back a 404 status code on error as requested.

However, you did ask good questions and file PRs basically the right way. Good job! Excited to see what you do on the upcoming ones.
