### ISSUE TITLE
(2nd) Implement the "like" trigger and rendering in the client

### ISSUE THREAD

**Issue by h4w5** [h4w5/wdinstagram_collaboration_challenge#5]
Here is what needs to be done:

While I have made sure that the API is working to add a like to an entry, we need to make sure the client can access this endpoint and re-render the entry!

You must:

1. Identify and check all of the triggers are firing for the ***like*** entry event:
   - [after the page loads from the server][t1]
   - [after rendering (loading) all entries by clicking on the "All Entries" tab][t2]
   - [after rendering a single entry's show "page"][t3]
2. **Write out the AJAX request to update the entry by liking it.** [The function stub is here][like]. The route is already written on the server side, and should be working: both [it's route][route] and it's [handler][handler].
3. Make sure that, *after the request is successful*, **the page re-renders its likes to show that it has incremented**. You can use the JSON's `formattedLikes` property to help you with this.

When you are complete, it should look like:

<img src="https://i.imgur.com/s0imMxR.png" width="100"> &nbsp; **=> SHOULD BECOME =>** &nbsp; <img src="https://i.imgur.com/XOVOoIf.png" width="100">

> ***Note that 0 likes becomes 1 like!***

[t1]: https://github.com/h4w5/wdinstagram_challenge/blob/master/public/js/main.js#L34-L39
[t2]: https://github.com/h4w5/wdinstagram_challenge/blob/master/public/js/main.js#L110-L115
[t3]: https://github.com/h4w5/wdinstagram_challenge/blob/master/public/js/main.js#L125-L130
[like]: https://github.com/h4w5/wdinstagram_challenge/blob/master/public/js/main.js#L95
[route]: https://github.com/h4w5/wdinstagram_challenge/blob/master/routes/api_routes.js#L8
[handler]: https://github.com/h4w5/wdinstagram_challenge/blob/master/controllers/entries.js#L22-L46

**Comment by jgescobar** [comment]
Hi Phil! 

AAU I can like an entry. 

I am stuck because I dont really know where to start with this one. I dont believe we've had an example for likes. I tried to see if mumblr had anything but it did not. I also searched "how to make a like trigger on MEN stack / with Json / on the client side/ but I havent been successful with answers that help. Do you have any idea where or how I could start with solving the client side of this issue? Thanks Phil!

What have I already attempted in trying to make this work:
``` 
function likeEntry(entryId) {
  $likeButtons

  $entries.find(".like-link").on("click", function(evt)  {
       var entryId = $(evt.currentTarget).closest(".entry").attr("id");
       console.log("like triggered!", entryId);
    
         likeEntry(entryId);
}
```

**Comment by h4w5** [comment]
Ah, so for *triggering*, that isn't really a term of art for programmers, more just how I described *emitting an event to registered event listeners* (which to mea sounds really weird).

Step 1 above doesn't mean you need to write any code, just read the code and see what's happenning there.

It's step 2 where you have to write code, and the function you have to implement is linked there (https://github.com/h4w5/wdinstagram_challenge/blob/master/public/js/main.js#L95).

Take a look at the client-side of the feature you just implemented for an idea of how to write an AJAX function that will target the API. All you have to do is make a request to the right endpoint (also identified by a link in step 2 above).

**Comment by jgescobar** [comment]
AAU I would like the like button to stay on like when clicked. 

Error I continue to get:
404 (not found) Like failed. 
![](https://i.imgur.com/siAPaxo.png)

This is what I've tried: 
![](https://i.imgur.com/bGxahyG.png)

Is this the proper way to address a 404 code?

**Comment by h4w5** [comment]
Ah, so the 404 comes after, once you've got it working in the first place! So let's "table" that part.

It looks to me like the URL you are sending to is incorrect… Instead of the final `likeEntry` variable, it should be the string `"/likes"`.

Thanks for the well-documented error!

**Comment by jgescobar** [comment]
Hi again, 

AAU I would like the page to reRender and update with the new like once its clicked and successfully

What Im currently stuck on:
I was able to get the like function to log and not get any errors back but now my issue is not being able to get the re render aspect to work (part 3 of Issue 2). I can get the like to refresh by adding  reload window function but Im not sure if that will be considered passing. I hope so.

This is what my function looks like: 
<img src="https://i.imgur.com/wvljqJu.png" height="500" width="500">

Can i submit and get the points for functionality since it is functioning? lol

**Comment by h4w5** [comment]
Yes, you would get partial points! Feel free to submit a PR, for now, and
to work on the next one. You don't have to do them in order.

To get the rendering to work, write some jQuery to grab the like text on
the page and replace the number in it or the HTML of it!

**Comment by h4w5** [comment]
Also, the window reload is a good idea. Smart hack!

**Comment by h4w5** [comment]
1 point: good questions, feature implemented, submitted from branch.
